simulation_manager:
  ros__parameters:
    launch_package: cpp_robotics_sim_ros
    launch_file: interactive_control.launch.py

    # Controls the simulation launched by this manager.
    # The manager itself continues using wall time.
    managed_use_sim_time: true

    startup_grace_period: 4.0
    shutdown_timeout: 4.0
    kill_timeout: 1.5
